### ISSUE TITLE
Craete MaterialRaisedButton with Python

### ISSUE THREAD

**Issue by FTeinz** [mixedCase/kivymd#2]
Hallo... At first NIce Work!

To my problem

I try to add a MaterialRaisedButton per Python like:
```
rom kivymd.theming import ThemeManager
from kivymd.button import MaterialRaisedButton

theme_cls = ThemeManager()

        self.button = MaterialRaisedButton(
        id = "raised_button",
        text= "Login",
        elevation_normal= 2,
        opposite_colors= True,
        size_hint= (None, None),
        size= (dp(110), dp(36)),
        pos_hint= {'center_x': 0.75, 'center_y': 0.3})  
        self.add_widget(self.button)
```
I get 

```
 Traceback (most recent call last):
   File "D:\Eigene Dateien\Downloads\KivyMD-master\window.py", line 111, in <module>
     FTCrypt().run()
   File "C:\Kivy-1.9.0-py2.7-win32-x64\kivy27\kivy\app.py", line 798, in run
     root = self.build()
   File "D:\Eigene Dateien\Downloads\KivyMD-master\window.py", line 107, in build
     sm.add_widget(ScreenOne(name='screen1'))
   File "D:\Eigene Dateien\Downloads\KivyMD-master\window.py", line 73, in __init__
     text= "Login")
   File "D:\Eigene Dateien\Downloads\KivyMD-master\kivymd\button.py", line 204, in __init__
     super(MaterialRaisedButton, self).__init__(**kwargs)
   File "D:\Eigene Dateien\Downloads\KivyMD-master\kivymd\theming.py", line 343, in __init__
     super(ThemableBehavior, self).__init__(**kwargs)
   File "D:\Eigene Dateien\Downloads\KivyMD-master\kivymd\elevationbehaviour.py", line 70, in __init__
     super(ElevationBehaviour, self).__init__(**kwargs)
   File "C:\Kivy-1.9.0-py2.7-win32-x64\kivy27\kivy\uix\behaviors.py", line 105, in __init__
     super(ButtonBehavior, self).__init__(**kwargs)
   File "C:\Kivy-1.9.0-py2.7-win32-x64\kivy27\kivy\uix\anchorlayout.py", line 68, in __init__
     super(AnchorLayout, self).__init__(**kwargs)
   File "C:\Kivy-1.9.0-py2.7-win32-x64\kivy27\kivy\uix\layout.py", line 66, in __init__
     super(Layout, self).__init__(**kwargs)
   File "C:\Kivy-1.9.0-py2.7-win32-x64\kivy27\kivy\uix\widget.py", line 271, in __init__
     Builder.apply(self)
   File "C:\Kivy-1.9.0-py2.7-win32-x64\kivy27\kivy\lang.py", line 1872, in apply
     self._apply_rule(widget, rule, rule)
   File "C:\Kivy-1.9.0-py2.7-win32-x64\kivy27\kivy\lang.py", line 1925, in _apply_rule
     rule.canvas_root, rootrule)
   File "C:\Kivy-1.9.0-py2.7-win32-x64\kivy27\kivy\lang.py", line 2139, in _build_canvas
     '{}: {}'.format(e.__class__.__name__, e), cause=tb)
 kivy.lang.BuilderException: Parser: File "<inline>", line 45:
 ...
      43:               Clear
      44:               Color:
 >>   45:                       rgba: self.background_color_disabled if self.disabled else                      (self.background_color if self.state == 'normal' else self.background_color_down)
      46:               Rectangle:
      47:                       size: self.size
 ...
 BuilderException: Parser: File "<inline>", line 45:
 ...
      43:               Clear
      44:               Color:
 >>   45:                       rgba: self.background_color_disabled if self.disabled else                      (self.background_color if self.state == 'normal' else self.background_color_down)
      46:               Rectangle:
      47:                       size: self.size
 ...
 AttributeError: 'MaterialRaisedButton' object has no attribute 'background_color'
   File "C:\Kivy-1.9.0-py2.7-win32-x64\kivy27\kivy\lang.py", line 1649, in create_handler
     return eval(value, idmap)
   File "<string>", line 45, in <module>
   File "kivy\weakproxy.pyx", line 19, in kivy.weakproxy.WeakProxy.__getattr__ (kivy\weakproxy.c:1101)
     return getattr(self.__ref__(), name)

   File "C:\Kivy-1.9.0-py2.7-win32-x64\kivy27\kivy\lang.py", line 2133, in _build_canvas
     key, value, prule, idmap, True)
   File "C:\Kivy-1.9.0-py2.7-win32-x64\kivy27\kivy\lang.py", line 1654, in create_handler
     cause=tb)
```

What is wrong here?

**Comment by mixedCase** [comment]
Not sure what's going on, the attribute should be there. Could you post the code for a small application that replicates the bug? I'm a bit short on time to work on the project.

**Comment by FTeinz** [comment]
Thanks for the quick response. Here is a example
```
import kivy
kivy.require('1.8.0')

from kivy.app import App
from kivy.uix.screenmanager import Screen, ScreenManager 
from kivy.uix.relativelayout import RelativeLayout
from kivy.metrics import dp
from kivymd.theming import ThemeManager
from kivymd.label import MaterialLabel
from kivymd.dialog import Dialog
from kivymd.textfields import SingleLineTextField
from kivymd.button import MaterialRaisedButton
sm = ScreenManager()

class ScreenOne(Screen):
    def __init__ (self,**kwargs):
        super (ScreenOne, self).__init__(**kwargs)

        #Modal work fine
        content = MaterialLabel(font_style='Body1',
        theme_text_color='Secondary',
        text="Hallo ",
        valign='top')

        content.bind(size=content.setter('text_size'))   
    
        self.dialog = Dialog(title="Login erfolgreich!",
        content=content,
        size_hint=(.8, None),
        height=dp(200),
        auto_dismiss=False)
        #self.dialog.open()
        
        
        #Button don't work
        self.button = MaterialRaisedButton(
        id = "raised_button",
        text= "Login",
        elevation_normal= 2,
        opposite_colors= True,
        size_hint= (None, None),
        size= (dp(110), dp(36)),
        pos_hint= {'center_x': 0.75, 'center_y': 0.3})  
        self.add_widget(self.button)       

        
class ScreenTwo(Screen):
    def __init__(self,**kwargs):
        super (ScreenTwo,self).__init__(**kwargs)
        
        
class TestApp(App):
    theme_cls = ThemeManager()
    def build(self):
           
        sm.add_widget(ScreenOne(name='screen1'))
        return sm 
 
if __name__ == '__main__':
    TestApp().run()
```
I´m not advanced on Kivy and english sorry.
The modal work but the button dosn`t.
Thanks a lot

**Comment by mixedCase** [comment]
Well with regards to the first one which is the one that corresponds with this issue, I'm not sure what's wrong. Tried a few things to fix it with no results. Right now (this is super alpha code, I'm going to break a lot of stuff in the following month for example) we do everything from kv lang and Kivy does some things in confusing/undocumented ways when running code from Python so without sitting down and tackling this I can't say what it could be or how to fix it. 

In the second one, you declared theme_cls as a local variable, when it should be an App property ;)

**Comment by FTeinz** [comment]
Sorry... could you tell me how to init the your theme in the right way for the second sample :relaxed:
thanks

**Comment by mixedCase** [comment]
Change this:

    presentation = Builder.load_string(login_kv)

    class MainApp(App):
        def build(self):
            theme_cls = ThemeManager()
            return presentation

to this:

    class MainApp(App):
        theme_cls = ThemeManager()
        def build(self):
            return Builder.load_string(login_kv)

**Comment by FTeinz** [comment]
:+1: Thanks a lot my friend 
certainly I will have some more questions is it possible to contact you on a nother way?

**Comment by mixedCase** [comment]
To be frank with you, I don't really offer support for this, as this is early-alpha quality software; we haven't even written any significant documentation yet.

Plus this is an old repository of mine, the official one is at https://github.com/kivymd/KivyMD

In any case, until release 0.5 is made all code falls under *caveat emptor* category.

**Comment by FTeinz** [comment]
how to set the theme_cls.primary_color manually?
I have try it like:
```
class TestApp(App):
    theme_cls = ThemeManager()
    def build(self):
        self.theme_cls.theme_style = 'Dark'
        self.theme_cls.primary_color = (1, 0, 0, 1)
        sm = ScreenManager()
        sm.add_widget(ScreenOne(name='screen1'))
        return sm 
```
...and direct in your script to resolve the 

```
      43:               Clear
      44:               Color:
 >>   45:                       rgba: self.background_color_disabled if self.disabled else                      (self.background_color if self.state == 'normal' else self.background_color_down)
      46:               Rectangle:
      47:                       size: self.size
 ...
 BuilderException: Parser: File "<inline>", line 45:
 ...
      43:               Clear
      44:               Color:
 >>   45:                       rgba: self.background_color_disabled if self.disabled else                      (self.background_color if self.state == 'normal' else self.background_color_down)
      46:               Rectangle:
      47:                       size: self.size
 ...
 AttributeError: 'MaterialRaisedButton' object has no attribute 'background_color'
```
error?

thanks a lot

**Comment by FTeinz** [comment]
if I try I get:
```
   File "D:\Eigene Dateien\Desktop\secure\windownew.py", line 76, in build
     self.theme_cls.primary_color = (1, 0, 0, 1)
   File "kivy\properties.pyx", line 397, in kivy.properties.Property.__set__ (kivy\properties.c:4680)
   File "kivy\properties.pyx", line 1350, in kivy.properties.AliasProperty.set (kivy\properties.c:21715)
   File "kivy\properties.pyx", line 1314, in kivy.properties.AliasProperty.__read_only (kivy\properties.c:20661)
 AttributeError: property is read-only
```
Is there a trick to write this read-only property :smile: ?

**Comment by AndersHogqvist** [comment]
Hello! 

Primary color is based on the primary_pallette and can not be set explicitly. You can however customize the hue by setting primary_hue, primary_light_hue and primary_dark_hue. You have the same options for accent_pallette. 

The reason for this is that in a Material Designed app, there is a certain color scheme based on the above options. If you choose a primary_pallette and a accent_pallette, you automatically get certain colors to use on various elements and that are more or less guaranteed to look nice together (since they are calculated by the people responsible for Google Material Design). I suggest you read the documentation on Google MD:

https://www.google.com/design/spec/material-design/introduction.html

If you like to change the color of specific elements, you have to do that outside of KivyMD. 

Best regards, 
Anders

**Comment by FTeinz** [comment]
In my opinion is Kivymd the colors schemes are stored kivymd filesystem or I'm wrong. The problem thems to be to do with the fetching of the background-color.
Best regards back

**Comment by mixedCase** [comment]
@FTeinz Could you try to rephrase the question? In any case, I will repeat what Anders said, you should read the Material Design spec. You *cannot* directly choose any color you want, in KivyMD you have to set a palette according to this: https://www.google.com/design/spec/style/color.html#color-color-palette
